export const DATA_DEFINITION = [
    {
        "Id": 1,
        "firstName": "Halie",
        "lastName": "Yakhin",
        "email": "hyakhin0@webeden.co.uk",
        "phone": "976-537-7298"
      }, {
        "Id": 2,
        "firstName": "Ardra",
        "lastName": "Babcock",
        "email": "ababcock1@accuweather.com",
        "phone": "800-560-2744"
      }, {
        "Id": 3,
        "firstName": "Gretal",
        "lastName": "Cape",
        "email": "gcape2@stanford.edu",
        "phone": "133-547-8368"
      }, {
        "Id": 4,
        "firstName": "Jilli",
        "lastName": "Bethune",
        "email": "jbethune3@smugmug.com",
        "phone": "750-550-2906"
      }, {
        "Id": 5,
        "firstName": "Simone",
        "lastName": "Shalliker",
        "email": "sshalliker4@sogou.com",
        "phone": "716-142-6783"
      }, {
        "Id": 6,
        "firstName": "Umberto",
        "lastName": "Matyasik",
        "email": "umatyasik5@si.edu",
        "phone": "563-467-9944"
      }, {
        "Id": 7,
        "firstName": "Benny",
        "lastName": "Zorzenoni",
        "email": "bzorzenoni6@baidu.com",
        "phone": "534-930-0541"
      }, {
        "Id": 8,
        "firstName": "Gerard",
        "lastName": "Wallbutton",
        "email": "gwallbutton7@guardian.co.uk",
        "phone": "606-219-1534"
      }, {
        "Id": 9,
        "firstName": "Wilmer",
        "lastName": "Peckham",
        "email": "wpeckham8@cbc.ca",
        "phone": "614-241-5288"
      }, {
        "Id": 10,
        "firstName": "Teodorico",
        "lastName": "Somers",
        "email": "tsomers9@paginegialle.it",
        "phone": "932-880-8844"
      }, {
        "Id": 11,
        "firstName": "Harriette",
        "lastName": "Aikman",
        "email": "haikmana@over-blog.com",
        "phone": "488-432-6010"
      }, {
        "Id": 12,
        "firstName": "Lemar",
        "lastName": "Lars",
        "email": "llarsb@google.pl",
        "phone": "940-940-1447"
      }, {
        "Id": 13,
        "firstName": "Donnie",
        "lastName": "Gartin",
        "email": "dgartinc@uiuc.edu",
        "phone": "838-627-7401"
      }, {
        "Id": 14,
        "firstName": "Giavani",
        "lastName": "Stearns",
        "email": "gstearnsd@netscape.com",
        "phone": "887-347-4309"
      }, {
        "Id": 15,
        "firstName": "Dukie",
        "lastName": "Petroulis",
        "email": "dpetroulise@google.co.uk",
        "phone": "125-254-1667"
      }, {
        "Id": 16,
        "firstName": "Vasili",
        "lastName": "Frarey",
        "email": "vfrareyf@typepad.com",
        "phone": "525-957-8877"
      }, {
        "Id": 17,
        "firstName": "Jarid",
        "lastName": "McDonand",
        "email": "jmcdonandg@admin.ch",
        "phone": "608-239-9893"
      }, {
        "Id": 18,
        "firstName": "Myrilla",
        "lastName": "Fantone",
        "email": "mfantoneh@yolasite.com",
        "phone": "652-428-1547"
      }, {
        "Id": 19,
        "firstName": "Eudora",
        "lastName": "Hinstock",
        "email": "ehinstocki@surveymonkey.com",
        "phone": "561-405-8522"
      }, {
        "Id": 20,
        "firstName": "Issi",
        "lastName": "Davage",
        "email": "idavagej@tumblr.com",
        "phone": "913-863-3127"
      }
]